=== j3d/j3dtools/src/config/file_input.dtd
<!--
   This simple DTD describes file input information for the j3d.org 
   FileInputDevice implementation. A very simple form, it just says to 
   have X sensors and then defines the data points for each sensor.
-->

<!ELEMENT input_data "(sensors_data)+">

<!-- 
  Describes the list of sensor information. The number is how many sensor
  objects we should use. Allows us to define extras and not use them in testing
-->

<!ELEMENT sensor_info (sensor)* >
<!ATTLIST sensor_info number CDATA #FIXED>


<!--
   Description of an individual sensor. The coordinates are defines as being a
   series of 3 points in the PCDATA of this element. The index is the sensor
   number to be used and corresponds to the device's getSensor(int) reply. 
   time is the amount of time for a single loop - in seconds (fractions
   permitted). Loops is the number of loops to perform. 0 says to not loop.
-->

<!ELEMENT sensor (sensor-data+ , button*)? >
<!ATTLIST sensor
  index CDATA #REQUIRED
  time  CDATA #REQUIRED
  loops CDATA "0"
  buttons CDATA "0"
>

<!ELEMENT sensor-data EMPTY>
<!ATTLIST sensor-data
  position CDATA #REQUIRED
  time     CDATA #REQUIRED
>

<!ELEMENT button (button-data)+ >
<!ATTLIST button 
  index CDATA #REQUIRED
>

<!ELEMENT button-data EMPTY>
<!ATTLIST button-data
  time  CDATA #REQUIRED
  value CDATA "0"
>

=== j3d/j3dtools/test/file_input.xml
<?xml version="1.0"?>
<!DOCTYPE X3D SYSTEM "http://www.j3d.org/xml/file_input.dtd">
<input_data>
  <sensor-info number="1">
    <sensor buttons="1" index="0" time="10" loops="0">
      <sensor-data position="0 0 0" time="0"/>
      <sensor-data position="0 1 0" time="2.5"/>
      <sensor-data position="1 1 0" time="5"/>
      <sensor-data position="1 0 0" time="7.5"/>
      <sensor-data position="0 0 0" time="10"/>
      <button index="0">
        <button-data value="0" time="0">
        <button-data value="1" time="1.5">
        <button-data value="0" time="1.6">
      </button>
    </sensor>
  </sensor_data>
</input_data>
